name: di_container
description: Dart library for dependency injection with the container.
version: 1.0.0
author: phamnhuvu <phamnhuvu.dev@gmail.com>
# homepage: https://www.example.com

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
