name: di_container
description: Dart library for dependency injection with the container. Easy to register and get get dependency without assign dependency's type , except you want cast type, you have to assign dependency's type.
version: 1.0.2
author: phamnhuvu <phamnhuvu.dev@gmail.com>
homepage: https://github.com/phamnhuvu-dev/dart_di_container

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
